name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'extras/images/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS Latest Clang",
            os: macos-latest,
            artifact: "macos_clang.7z",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++"
          }

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Verify
        run: |
          rustc --version

      - name: Install Toolchains
        run: |
          rustup target add aarch64-apple-ios --toolchain nightly
          rustup target add aarch64-apple-ios-sim --toolchain nightly
          rustup target add aarch64-linux-android --toolchain nightly

      - name: Build
        run: make
